[package]
name = "loregui"
version = "0.1.0"
edition = "2021"

[lib]
name         = "lorecore"
crate-type   = ["rlib", "cdylib"]

[dependencies]
diesel = {version = "2.0.3", features = ["sqlite"]}
diesel_migrations = {version = "2.0.0"}
iced = "0.9.0"
iced_aw = { version = "0.5.0", default-features = false, features = ["card", "modal", "selection_list"] }
iced_lazy = "0.6.1"
libc = "0.2.140"
preferences = {version = "1.1.0"}
rfd = "0.11.3"
rusqlite = { version = "0.29.0", features = ["bundled"] }

[build-dependencies]
cbindgen = "0.24.3"